services:
  app:
    image: jpedrofsgs/gerenciador-de-projetos-v2:1.0
    container_name: gerenciador-de-projetos-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    container_name: gerenciador-de-projetos-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7.4.1-alpine
    container_name: gerenciador-de-projetos-redis
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
