allowed:
    origins: ${ALLOWED_ORIGINS}
jwt:
    private:
        key: file:/run/secrets/private_key
    public:
        key: file:/run/secrets/public_key
spring:
    config:
        import:
            - optional:file:.env[.properties]
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
    datasource:
        password: ${POSTGRES_PASSWORD}
        username: ${POSTGRES_USER}
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: update